import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideBar from "./_component/sideBar";
import "./globals.css";

const geistSans = Inter({
  subsets: ["latin"],
  variable: "--font-geist-sans",
  display: "auto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`}>
        <div className="flex h-full gap-8">
          <SideBar />
          {children}
        </div>
      </body>
    </html>
  );
}
