import SideBar from "@/app/_components/sideBar";
import { Toaster } from "@/app/_components/ui/sonner";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


const geistSans = Inter({
  subsets: ["latin"],
  variable: "--font-geist-sans",
  display: "auto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`}>
        <div className="flex h-full">
          <SideBar />
          {children}
          <Toaster  position="top-right"  richColors theme="light"/>
        </div>
      </body>
    </html>
  );
}
